### ISSUE TITLE
Optimize MassPM Function

### ISSUE THREAD

**Issue by HDVinnie** [HDInnovations/UNIT3D#238]
- UNIT3D Version: 1.6.4
- Laravel Version: 5.6.12
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7

### Description:
Current functionality is not realistic for a site with many members. Sending a MassPM to 10K members is running a massive amount of queries at once resulting in timeouts.

### Steps To Reproduce:
Send MassPM to all users on site. If site has ALOT of members you will most likely receive a NGINX TIMEOUT ERROR.

### Possible Fix:
There is a better way to approach this. 

1) We could just create a message and not send it. Then have pivot table message_user, which will hold IDs of users and read messages. So when a user logs into the system, the system will show all messages which don't have an entry in the pivot table as unread messages so instead of executing 10k queries all at once every user object will be handling its own unread messages upon user login?

2) Chunking?

**Comment by HDVinnie** [comment]
closed in https://github.com/HDInnovations/UNIT3D/pull/452

**Comment by LayerCorp** [comment]
I was about to open a new issue for enhancement about this, because we need to send MASS PM but with option to select usersgroups who will get the PM, but found this.

Doing this you can somehow fix this issue because you can send in parts, I really would love to have the option to select what usergroups are receiving the staff mass PM.
