### ISSUE TITLE
Movie and TV categories rerouting

### ISSUE THREAD

**Issue by STiCKYFiNGAZZ** [HDInnovations/UNIT3D#530]
### Issue Type
- [x] Feature Idea
- [x] Enhancement

### End User Info
-- UNIT3D Version: #.#.#

-- Laravel Version: #.#.#

Request to have movie and tv categories reroute to selected view, also retains search functionality...

**Comment by HDVinnie** [comment]
Not sure Im following what you mean. Could possible give video example?

**Comment by STiCKYFiNGAZZ** [comment]
When using category view, only shows movies and tv in default "torrent" view, as opposed to user defined view ie. Grouping, cards, etc. So what I did was create dropdown "buttons" for browse (browse all) and movies and tv categories. What I want to accomplish is when a user clicks on tv or movies, it shows their defined view

**Comment by STiCKYFiNGAZZ** [comment]
[![Screenshot from Gyazo](https://gyazo.com/3cabf401f56925acde6160ef53fb1e92/raw)](https://gyazo.com/3cabf401f56925acde6160ef53fb1e92)

[![Screenshot from Gyazo](https://gyazo.com/af881f87bc928e8fe8fc01163157a9a0/raw)](https://gyazo.com/af881f87bc928e8fe8fc01163157a9a0)

As it stands, when choosing a category, it shows list view, where my request was to have the view as what the user has defined as their default, ie, cards, groupings, etc... also when you using categories, cannot choose filters... I can see how my original request could be confusing

**Comment by STiCKYFiNGAZZ** [comment]
What I have noticed as well is that if you use filters and highlight just the main category, it does show the user defined view...

[![Screenshot from Gyazo](https://gyazo.com/417d004073db29926c2612706fa45015/raw)](https://gyazo.com/417d004073db29926c2612706fa45015)

**Comment by HDVinnie** [comment]
Ok. I understand. However the Categories page here.
[![Screenshot from Gyazo](https://i.postimg.cc/wvHf0k82/Screen-Shot-2019-03-08-at-4-49-11-PM.png)](https://i.postimg.cc/wvHf0k82/Screen-Shot-2019-03-08-at-4-49-11-PM.png)

Are of there own and the results of when clicking is its own view with no search options. Just meant as way to view that categories torrents in desc order. Otherwise user would just use Lists, Cards or Grouping view and select a category filter.

https://github.com/HDInnovations/UNIT3D/tree/master/resources/views/category

**Comment by STiCKYFiNGAZZ** [comment]
I understand. You can close this request =)
