### ISSUE TITLE
Error 500: Internal Server Error!

### ISSUE THREAD

**Issue by MaleiSiyin** [HDInnovations/UNIT3D#582]
Show successful installation, an error is reported when accessing

```
Error 500: Internal Server Error!
Our server encountered an internal error. 
Sorry For The Inconvenience
Go Home
```

[https://s2.ax1x.com/2019/02/20/kREvy8.png](url)
[https://s2.ax1x.com/2019/02/20/kREjQf.png](url)

**Comment by HDVinnie** [comment]
Looking at the image the CSS and JS didnt seem to compile. Were there any `errors/warnings` during the install process?

Also. Before you come here to get support for a Error 500: Internal Server Error! Please prepare yourself with the actual error either from the `storage/logs` directory or if accessible the log viewer built into the codebase which can be accessed from the staff dashboard. IE: https://yourdomain.com/staff/log-viewer/logs

Anyone asking for support for a Error 500: Internal Server Error! will be ignored otherwise as ERROR 500 is generic and tell us nothing useful.

**Comment by HDVinnie** [comment]
Hi @MaleiSiyin ,

You've created an issue, but haven't provided any details to allow the community to assist you. To prevent issue tracker clutter, this issue will now be closed. Please provide the information needed below and I will re-open this issue if needed.
