### ISSUE TITLE
Problem editing conf files using dashboard

### ISSUE THREAD

**Issue by tuxfrw** [HDInnovations/UNIT3D#602]
### Issue Type
- [x] Bug Report

### End User Info
-- UNIT3D Version: 1.19

-- Laravel Version: 5.7.25

-- PHP Version: 7.2.15

-- Database Driver & Version: Mariadb 10.2.22

-- Web Server Driver & Version: nginx 1.10.3

-- OS Driver and Version: Debian 9 

### Expected Behavior:
Edit conf files using dashboard

### Actual Behavior:
When I click to edit any configuration file, a black window appears. No errors in laravel and logs.

### Steps To Reproduce The Problem:
1.
2.
3.

**Comment by HDVinnie** [comment]
`php artisan clear:all_cache` <--- clear your cache
make your config changes
`php artisan set:all_cache` <--- to recache if you want performance boost

We will probably add buttons in config manager so can set and clear cache right from manager.

**Comment by tuxfrw** [comment]
This I did and it worked. I'm saying it's by the dashboard editing tool.
https://i.imgur.com/NuepdvS.png

**Comment by aronpc** [comment]
+1

**Comment by HDVinnie** [comment]
@tuxfrw thanks. I will look into it.

**Comment by HDVinnie** [comment]
So I was able to hunt down the issue. Config Manager broke due to https://github.com/HDInnovations/UNIT3D/commit/a3b6d48560033ed29aed9126e6936b947c21aaef

`resources/views/vendor/infinety/configmanager/index.blade.php` will need to be refactored to use modals instead of tooltips it appears. Ill try to push a fix soon.

**Comment by Yavzkesta** [comment]
+1

**Comment by singularity43** [comment]
Closed in #617
