### ISSUE TITLE
Creating new backup fails

### ISSUE THREAD

**Issue by yourguessismine** [HDInnovations/UNIT3D#603]
### Issue Type
- [x] Bug Report

### End User Info
-- UNIT3D Version: 1.9.0

-- Laravel Version: 5.7.25

-- PHP Version: 7.2.9

-- Database Driver & Version: MySQL 5.7.23

-- Web Server Driver & Version: nginx/1.15.0

-- OS Driver and Version: Ubuntu 18.04.1

When attempting to create a backup an error is received. I have tried this on the demo site with the same result.

Allowed memory size of 134217728 bytes exhausted (tried to allocate 60747152 bytes) {"userId":3,"email":"none@none.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 60747152 bytes) at /var/www/html/vendor/nelexa/zip/src/PhpZip/Crypto/WinZipAesEngine.php:254)

### Steps To Reproduce The Problem:
1. Create Backup
2.
3.

**Comment by HDVinnie** [comment]
As noted in Commit the encryption and password protection of backups is memory heavy if you have a larger site/db. You need to tune PHP. Raise the memory_limit. You can see tuning/perfomance tips in our discord in #tuts channel.

You could also also do something like `ini_set('memory_limit', '2048M');` (raise if needed). Adding that to `app/Helpers/BackupPassword.php` at line 32.

That would solve any memory_limits your server is facing because not tuned.
