### ISSUE TITLE
can't create backup

### ISSUE THREAD

**Issue by christ84** [HDInnovations/UNIT3D#861]
### Issue Type
- [x] Bug Report
I can't create full & files backup, it stops after a while

### End User Info
-- UNIT3D Version: 1.9.4

-- Laravel Version: Ver. 6.0.3

-- PHP Version: php7.3.9-1+ubuntu18.04.1+deb.sury

### Steps To Reproduce The Problem:
1.https://siter/staff_dashboard/backup

**Comment by HDVinnie** [comment]
This is probably because your PHP memory_limit needs to be increased.

SSH to your server and run:
`sudo nano /etc/php/7.3/fpm/php.ini`

Find:
```
;This sets the maximum amount of memory in bytes that a script is allowed to allocate
memory_limit = xxxx
```

Increase it to something like `memory_limit = 1024M`

save and exit

Restart PHP
`sudo systemctl restart php7.3-fpm`


If it still hangs then its just two big of a backup to do from front-end. You can ssh to your server. cd to the project root and then run these commands.

You can do a full backup of your app by running:
`php artisan backup:run`

If you only need to backup the db, run:
`php artisan backup:run --only-db`

If you only need to backup the files, and want to skip dumping the databases, run:
`php artisan backup:run --only-files`
